from kgl.io import Metrics
from tools import exp_table


def _m(exp: str, run: str, cv: float, base: str = "none", notes: str = "") -> Metrics:
    return Metrics(
        exp=exp,
        base=base,
        run=run,
        cv=cv,
        cv_folds=[cv],
        metric="accuracy",
        config={},
        argv=[],
        git_commit="abc",
        started_at="2026-09-20T10:00:00",
        finished_at="2026-09-20T10:01:00",
        notes=notes,
    )


def test_render_sorts_rows_and_joins_lb_by_exp_and_run():
    metrics = [_m("exp001_b", "default", 0.82), _m("exp000_a", "default", 0.80), _m("exp000_a", "1a2b3c4d", 0.81)]
    submissions = [{"exp": "exp000_a", "run": "default", "public_lb": "0.7900"}]
    out = exp_table.render(metrics, submissions)
    lines = [ln for ln in out.splitlines() if ln.startswith("| exp0")]
    assert lines == [
        "| exp000_a | 1a2b3c4d | 0.8100 |  | none | accuracy |  | output/exp000_a/1a2b3c4d |",
        "| exp000_a | default | 0.8000 | 0.7900 | none | accuracy |  | output/exp000_a/default |",
        "| exp001_b | default | 0.8200 |  | none | accuracy |  | output/exp001_b/default |",
    ]


def test_render_excludes_debug_runs_by_default():
    metrics = [_m("exp000_a", "debug", 0.5), _m("exp000_a", "default", 0.8)]
    out = exp_table.render(metrics, [])
    assert "| exp000_a | debug |" not in out
    assert "| exp000_a | default |" in out


def test_render_starts_with_a_generated_marker():
    assert exp_table.render([], []).splitlines()[0].startswith("<!-- generated by `just exp-table`")


def test_parse_submissions_reads_table_rows():
    text = (
        "# Submissions\n\n| date | exp | run | cv | public_lb | message | kernel_version | file |\n"
        "|---|---|---|---|---|---|---|---|\n"
        "| 2026-09-20 | exp000_a | default | 0.8000 | 0.7900 | baseline |  | submission.csv |\n"
    )
    rows = exp_table.parse_submissions(text)
    assert rows == [
        {
            "date": "2026-09-20",
            "exp": "exp000_a",
            "run": "default",
            "cv": "0.8000",
            "public_lb": "0.7900",
            "message": "baseline",
            "kernel_version": "",
            "file": "submission.csv",
        }
    ]
