"""Render docs/experiments.md from every output/<exp>/<run>/metrics.json plus LB scores from docs/submissions.md.

Usage: uv run python -m tools.exp_table [--include-debug]
"""

from dataclasses import dataclass
from pathlib import Path

import tyro

from kgl.io import Metrics, read_metrics

HEADER = "<!-- generated by `just exp-table` from output/*/*/metrics.json and docs/submissions.md; do not edit -->"
COLUMNS = ("exp", "run", "cv", "lb", "base", "metric", "note", "path")


def load_metrics(output_dir: Path) -> list[Metrics]:
    return [read_metrics(p) for p in sorted(output_dir.glob("*/*/metrics.json"))]


def parse_submissions(text: str) -> list[dict[str, str]]:
    """Read the rows of the markdown table in docs/submissions.md into dicts keyed by the header."""
    rows: list[dict[str, str]] = []
    header: list[str] | None = None
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if header is None:
            header = cells
            continue
        if all(set(c) <= {"-", ":"} for c in cells):
            continue
        rows.append(dict(zip(header, cells, strict=True)))
    return rows


def render(metrics: list[Metrics], submissions: list[dict[str, str]], include_debug: bool = False) -> str:
    lb_by_run = {(s["exp"], s["run"]): s["public_lb"] for s in submissions}
    rows = sorted((m for m in metrics if include_debug or m.run != "debug"), key=lambda m: (m.exp, m.run))
    lines = [HEADER, "", "| " + " | ".join(COLUMNS) + " |", "|" + "---|" * len(COLUMNS)]
    for m in rows:
        cells = (
            m.exp,
            m.run,
            f"{m.cv:.4f}",
            lb_by_run.get((m.exp, m.run), ""),
            m.base,
            m.metric,
            m.notes,
            f"output/{m.exp}/{m.run}",
        )
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


@dataclass
class Args:
    include_debug: bool = False


def main(args: Args) -> None:
    root = Path(__file__).resolve().parents[1]
    submissions_md = root / "docs" / "submissions.md"
    submissions = parse_submissions(submissions_md.read_text()) if submissions_md.exists() else []
    out = root / "docs" / "experiments.md"
    out.write_text(render(load_metrics(root / "output"), submissions, include_debug=args.include_debug))
    print(out)


if __name__ == "__main__":
    main(tyro.cli(Args))
